image: docker:latest

services:
  - docker:dind
  
before_script:
  - apk update
  - apk add make
  
smoke-test:
  stage: test
  script:
    - make

deploy:
  stage: deploy
  script:
    - make deploy
