image: docker

stages:
  - build
  - deploy

before_script:
  - apt-get update -y && apt-get install ssh-agent
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SCALEWAY_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - docker-machine create --driver generic --generic-ip-address=212.47.231.85 --generic-ssh-user=root deploy
  - eval $(docker-machine env deploy)

bundle:
  stage: build
  script:
    - cd code/
    - docker-compose build

scaleway:
  stage: deploy
  script:
    - cd code/
    - docker-compose up
