version: '2'

services:
  data-collectors:
    build: data-collectors/
    links:
      - mongodb
    restart: always

  backend:
    build: backend/
    links:
      - mongodb

  frontend:
    build: frontend/
    links:
      - backend
    ports:
      - "80:80"

  mongodb:
    image: "mongo:latest"

